### ISSUE TITLE
Question: why not use sprites?

### ISSUE THREAD

**Issue by wstoettinger** [bendiksolheim/emojiarea#1]
Hey @bendiksolheim ! Great work you are doing on the emojiarea! I was just wondering why you don't use png sprites instead of separate png files? this looks like it results in a LOT of requests and slows down page loading.

cheers!
Wolfgang

**Comment by wstoettinger** [comment]
okay, I just saw you forked from a version which already converted the sprites into individual images. the original version uses sprites! might be worthy of considering.

**Comment by bendiksolheim** [comment]
Hello @wstoettinger !

That is a valid question. I have to admin that this repository is more or less dead, I have no intention of continuing with it. It was more of a test to see if it was possible at all to render emojis in a textarea in a predictable manner. Sadly, the project I was going to use it in decided not to implement this, so I stopped developing on it.

**Comment by wstoettinger** [comment]
Hey @bendiksolheim! Thanks for the info! I found your repo because it was the fork that seemed to have the most recent development of the original repo. I then decided to develop one from scratch inspired by OneSignal/emoji-picker and diy/jquery-emojiarea because nothing I could find offered the flexibility and functionality I was looking for while still maintaining some light weight (as far as this is possible with emoji libraries).

In case you need something similar in the future or you are curious, feel free to check out my repo here: https://github.com/wstoettinger/jquery.emojiarea.js 

I'm still working on the browser support, especially when it comes to copy, paste, undo and redo actions (As usual IE is a pain in the ass here!).

**Comment by bendiksolheim** [comment]
Glad you got things sorted :)  I’ll definitely keep your respository in mind!

Closing this, as you seem to have found a solution.
